### ISSUE TITLE
Missing indexed rewards in multiple occasions

### ISSUE THREAD

**Issue by evyatar-tres** [subscan-explorer/subscan-issue-tracker#72]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

Polkadot, Kusama

### Steps to reproduce

we're looking into another major reconciliation issue that has cross-substrate impact

In some scenarios, rewards are not indexed on the `/api/scan/account/reward_slash` endpoint
for example:
This account: [](https://kusama.subscan.io/account/DDZ8jAMAscud4SZzUNXsogJEynucssyndVFnHTHRnoWtsMq)
is defined as this account's reward destination
[](https://kusama.subscan.io/account/D6ABm6ze7WmuE9fh2CvqpJyND1LuVDAp4o4Vsb29cG3T1Xf)
(set here: https://kusama.subscan.io/extrinsic/6844837-5)
We can see this balances::deposit event:
[](https://kusama.subscan.io/extrinsic/17525090-11?event=17525090-131)
and this staking::rewarded event:
[](https://kusama.subscan.io/extrinsic/17525090-11?event=17525090-132)
Those are both associated (account D6A receives the reward, but it is deposited into DDZ account and therefore should be indexed under the reward_slash endpoint)
```
curl -X POST 'https://kusama.api.subscan.io/api/scan/account/reward_slash' \
  --header 'Content-Type: application/json' \
  --header 'X-API-Key: XXX' \
  --data-raw '{
    "row": 20,
    "page": 0,
    "address": "DDZ8jAMAscud4SZzUNXsogJEynucssyndVFnHTHRnoWtsMq",
    "block_range" : "17525087-17525092"
  }'
```
This however works for all of the other rewards at this form (or most of them)
example of indexed reward: https://kusama.subscan.io/event?extrinsic=17512277-7&page=2
```
curl -X POST 'https://kusama.api.subscan.io/api/scan/account/reward_slash' \
  --header 'Content-Type: application/json' \
  --header 'X-API-Key: XXX' \
  --data-raw '{
    "row": 20,
    "page": 0,
    "address": "DDZ8jAMAscud4SZzUNXsogJEynucssyndVFnHTHRnoWtsMq",
    "block_range" : "17512276-17512278"
  }'
```

**Another example**
for this account:
https://polkadot.subscan.io/account/125wbXJRqFihZD1QW9wKLz2ZNkkjAc1XxMaJ59nno7TV7q2x)
[](https://polkadot.subscan.io/account/125wbXJRqFihZD1QW9wKLz2ZNkkjAc1XxMaJ59nno7TV7q2x)

This reward is not indexed:
https://polkadot.subscan.io/extrinsic/15107021-4?event=15107021-60
[](https://polkadot.subscan.io/extrinsic/15107021-4?event=15107021-60)

it has the relevant balance::deposit event but its not indexed in the reward_slash endpoint (or the v2 endpoint)
https://polkadot.subscan.io/extrinsic/15107021-4?event=15107021-59
[](https://polkadot.subscan.io/extrinsic/15107021-4?event=15107021-59)

### Expected output

Reward is indexed

### Actual output

Reward is not indexed

**Comment by freehere107** [comment]
@evyatar-tres Thanks for your feedback. We will check it as soon

**Comment by freehere107** [comment]
hi, @evyatar-tres This issue has been fixed.

**Comment by evyatar-tres** [comment]
Hi @freehere107 , i've seen the second example is now indexed (polkadot), but Kusama still does not work, can you take a look at the first cURL example?

this 
`curl -X POST 'https://kusama.api.subscan.io/api/scan/account/reward_slash' \
  --header 'Content-Type: application/json' \
  --header 'X-API-Key: XXX' \
  --data-raw '{
    "row": 20,
    "page": 0,
    "address": "DDZ8jAMAscud4SZzUNXsogJEynucssyndVFnHTHRnoWtsMq",
    "block_range" : "17525087-17525092"
  }'

returns [`]({"code":0,"message":"Success","generated_at":1694157798,"data":{"count":0,"list":null}})

**Comment by freehere107** [comment]
Hi, @evyatar-tres  Can you provide which rewards are not indexed?

**Comment by evyatar-tres** [comment]
Hi @freehere107 
After further investigation, it seems that events on specific dates were indexed incorrectly, I see a lot around mid-June (blocks  160830XX and  160254XX)

Please check the following pairs, the first is the reward event and the second is the deposit event (which is the reward stash)
it seems that the rewards are not indexed for the stashed mentioned here

Reward event: 16083015-300
Deposit event: 16083015-299

Reward event: 16025446-286
Deposit event: 16025446-285

Reward event: 16025447-152
Deposit event: 16025447-151

Reward event: 16083016-84
Deposit event: 16083016-83

Reward event: 16083016-185
Deposit event: 16083016-184

Reward event: 16083014-41
Deposit event: 16083014-40

**Comment by freehere107** [comment]
@evyatar-tres Is polkadot or kusama ?

**Comment by evyatar-tres** [comment]
@freehere107 those are polkadots

**Comment by freehere107** [comment]
hi, @evyatar-tres Thanks for your feedback. This issue has been fixed and the reward data has been reindexed.
