### ISSUE TITLE
Pure Proxy still displayed after removal

### ISSUE THREAD

**Issue by DrW3RK** [subscan-explorer/subscan-issue-tracker#97]
### Confirmation

- [X] My issue isn't already found on the issue tracker.
- [X] I have read the Subscan API documentation (if it seemed to be an API bug).

### Affected Network(s)

polkadot

### Steps to reproduce

Subscan explorer shows a proxy for this account https://polkadot.subscan.io/account/12tp6EoXFwAucagB9BrKqud5XfBFQKm4LHg48xARHQnjQsmk which is a Pure Proxy https://polkadot.subscan.io/account/12NY5cguZUHNm5hhAxLMZXMtnKT3LZttgxuieSkoqevgQp8b

But on-chain state shows that neither of these accounts have proxies

<img width="1429" alt="image" src="https://github.com/subscan-explorer/subscan-issue-tracker/assets/86818441/f8bba1eb-9724-40b0-8175-461b8ad8448d">

### Expected output

0 proxies associated with https://polkadot.subscan.io/account/12tp6EoXFwAucagB9BrKqud5XfBFQKm4LHg48xARHQnjQsmk and https://polkadot.subscan.io/account/12NY5cguZUHNm5hhAxLMZXMtnKT3LZttgxuieSkoqevgQp8b

### Actual output

1 proxy associated with https://polkadot.subscan.io/account/12tp6EoXFwAucagB9BrKqud5XfBFQKm4LHg48xARHQnjQsmk and https://polkadot.subscan.io/account/12NY5cguZUHNm5hhAxLMZXMtnKT3LZttgxuieSkoqevgQp8b

**Comment by freehere107** [comment]
@DrW3RK Thanks for report. We will fix it as soon

**Comment by cuckooemm** [comment]
We have fixed this issue, thanks for the feedback

**Comment by Juanma0x** [comment]
It seems the issue persists in Polkadot Asset Hub:

- "Proxy" account: https://assethub-polkadot.subscan.io/account/13B8A25wd7U8GZ57737pgHXxKoChMXWSw6ZSb2Ug3pbj4iNe
- "Proxied" account: https://assethub-polkadot.subscan.io/account/133t3gdpkJQaQC2J4uR8aGRgs7fJVkYcZnHnH9ivu4D1FxUT
- Killing extrinsic: https://assethub-polkadot.subscan.io/extrinsic/6324563-2
- Chain-state:
![image](https://github.com/subscan-explorer/subscan-issue-tracker/assets/120041850/0605141d-e70e-432f-bf6d-3bb4e33ab040)
